/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   mixins/etools-currency-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import { PolymerElement } from '@polymer/polymer';
export {EtoolsCurrency};


interface Constructor<T = {}> {
  new (...args: any[]) : T;
 }
/**
* Currency amount input. US format only.
*/
declare function EtoolsCurrency(base: Constructor<PolymerElement>):
{
 new (...args: any[]): {
   addCurrencyAmountDelimiter(value: any): any;
   displayCurrencyAmount(value: any, placeholder?: any, noOfDecimals?: any): any;
 }
} & Constructor<PolymerElement>;
